### ISSUE TITLE
[OJS 33]  branch submissionItemDeletion : get Error "An unexpected error has occurred. Please reload the page and try again."

### ISSUE THREAD

**Issue by forgive38** [lepidus/deleteIncompleteSubmissions#1]
Hello
first of all, thank you for this plugin 
I'm trying to use the submissionItemDeletion branch with ojs 3.3.0.14 :
the extra tab is added and so I have the list of incomplete submissions.
I have the rights to delete, but when I click on delete, after answering yes to the popup “Are you sure you want to permanently delete this submission?” I get the error “An unexpected error has occurred. Please reload the page and try again.”
(xhr : http://localhost:8099/index.php/publicknowledge/undefined/20 : see undefined in request)
Do you have the same problem?

when debugging I see that it's the variables passed to the component that are empty (apiUrl etc.).
I confess I don't know enough about Vue to find the problem.
If I pass the :components object and retrieve it in its entirety from the IncompleteSubmissionsListItem props, I do have access to the various properties, including apiUrl, but I think there are cleaner ways...
Thanks for your help  

(I update this version to be compliant with 3.4, but I have the same error)

**Comment by diegoabadan** [comment]
Hi @forgive38, thanks for your message.

This branch does not work and will be deleted. Please opt for the latest release compatible with the OJS you are using. Today for OJS 3.3.x it is this one:
https://github.com/lepidus/deleteIncompleteSubmissions/releases/tag/v0.1.3

I hope you are now successful in deleting the incomplete submissions.

**Comment by forgive38** [comment]
@diegoabadan 
For information, I concatenate your 2 versions of your plugin 
https://github.com/forgive38/deleteIncompleteSubmissions/tree/AddIncompleteSubmissionTab-3_4
I restrict these features to ROLE_ID_SITE_ADMIN and ROLE_ID_MANAGER
we use it with 3.4

**Comment by thiagolepidus** [comment]
Hello, @forgive38. Thanks for letting us know.

I've checked and the implementation in your fork is working correctly. 
If you have any questions, feel free to get in touch.

**Comment by diegoabadan** [comment]
@forgive38, feel free to send us a PR when you consider the feature ready for use.

Thank you!
