### ISSUE TITLE
OPS compatibility

### ISSUE THREAD

**Issue by Ppantaleo** [lepidus/deleteIncompleteSubmissions#2]
Hello, is it possible to use it in OPS 3.4? How to adapt it? Thank you.

**Comment by JhonathanLepidus** [comment]
Hello @Ppantaleo !

Thanks for this issue. We checked the plugin compatibility and found it was already compatible with OPS 3.4.0 on [Release v0.2.0](https://github.com/lepidus/deleteIncompleteSubmissions/releases/tag/v0.2.0). In our tests, it worked well in a OPS 3.4.0, so it should work for you as well.

**Comment by Ppantaleo** [comment]
Thanks @JhonathanLepidus Worked for us.

https://preprints.latarxiv.org/
